{
  "openapi": "3.0.1",
  "info": {
    "title": "Api CRUD ORDENES",
    "description": "Esta api te pemite administrar Ordenes",
    "contact": {
      "name": "Exequiel Ridolfi y Nahir Chandia",
      "email": "ridolfiexe17@gmail.com"
    },
    "version": "1"
  },
  "paths": {
    "/api/charge/{id}": {
      "put": {
        "tags": [
          "charge-controller"
        ],
        "summary": "Este endpoint se encargar de modificar una orden",
        "operationId": "updateCharge",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Orders"
              }
            }
          },
          "required": true
        },
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "500": {
            "description": "error de parametros"
          },
          "200": {
            "description": "Orden actualizado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Orders"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "charge-controller"
        ],
        "summary": "Este endpoint se encargar de borrar una orden",
        "operationId": "deleteChange",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "500": {
            "description": "error de parametros"
          },
          "200": {
            "description": "Orden borrado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Orders"
                }
              }
            }
          }
        }
      }
    },
    "/api/charge": {
      "get": {
        "tags": [
          "charge-controller"
        ],
        "summary": "Este endpoint se encargar de obtener todos las ordenes",
        "operationId": "getOrders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Orders"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "charge-controller"
        ],
        "summary": "Este endpoint se encargar de crear una orden",
        "operationId": "newCharge",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Orders"
              }
            }
          },
          "required": true
        },
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "200": {
            "description": "orden creado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Orders"
                }
              }
            }
          },
          "500": {
            "description": "error de parametros"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Change": {
        "required": [
          "sku",
          "customer",
          "deliveryAddress",
          "amount"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "sku": {
            "type": "string"
          },
          "customer": {
            "type": "string"
          },
          "deliveryAddress": {
            "type": "string"
          },
          "amount": {
            "minimum": 0,
            "exclusiveMinimum": false,
            "type": "string",
          }
        }
      }
    }
  }
}