{
  "openapi": "3.0.1",
  "info": {
    "title": "Nuestra primera api crud creada por java/Spring",
    "description": "Esta api te pemite administrar productos",
    "contact": {
      "name": "Exequiel Ridolfi",
      "email": "ridolfiexe17@gmail.com"
    },
    "version": "1"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/products/{id}": {
      "put": {
        "tags": [
          "product-controller"
        ],
        "summary": "Este endpoint se encargar de modificar un producto",
        "operationId": "modifyProduct",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "required": true
        },
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "500": {
            "description": "error de parametros"
          },
          "200": {
            "description": "Producto actualizado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "product-controller"
        ],
        "summary": "Este endpoint se encargar de borrar un producto",
        "operationId": "deleteProduct",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "500": {
            "description": "error de parametros"
          },
          "200": {
            "description": "Producto borrado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        }
      }
    },
    "/api/products": {
      "get": {
        "tags": [
          "product-controller"
        ],
        "summary": "Este endpoint se encargar de obtener todos los productos",
        "operationId": "getProducts",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Product"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "product-controller"
        ],
        "summary": "Este endpoint se encargar de crear un producto",
        "operationId": "newProduct",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "required": true
        },
        "responses": {
          "400": {
            "description": "error de  la respuesta"
          },
          "200": {
            "description": "Producto creado con exito",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          },
          "500": {
            "description": "error de parametros"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Product": {
        "required": [
          "description",
          "name",
          "price",
          "sku"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "sku": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "price": {
            "minimum": 0,
            "exclusiveMinimum": false,
            "type": "number",
            "format": "double"
          },
          "status": {
            "type": "boolean"
          }
        }
      }
    }
  }
}